# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-ListDetector
version:      1.00
version_from: lib/Mail/ListDetector.pm
installdirs:  site
requires:
    Carp:                          0
    Email::Abstract:               0
    Email::Valid:                  0.12
    Test::More:                    0.08
    URI:                           1.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
